
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package ucu;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SECCION = 2;
  public static final int error = 1;
  public static final int ELEMENTO = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SECCION",
  "ELEMENTO"
  };
}

